export const HOME_PATH = "/";
export const PROJECTS_PATH = "/projects";
export const MODEL_PATH = "/projects/model";
export const GAMESYSTEM_PATH = "/projects/gameSystem";
export const VISUALEFFECTS_PATH = "/projects/visualEffects";
export const MORE_PATH = "/projects/more";
export const RESUME_PATH = "/resume";
export const CONTACT_PATH = "/contact"
export const TEST_PATH ="/test"